import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'LogosSphere',
  description: 'Generated by create next app',
  icons: {
    icon: "/favicon.png"
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
